# Generated by Django 2.0.3 on 2018-06-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0003_matchkoef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='perc_to1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='perc_to2',
        ),
        migrations.AddField(
            model_name='player',
            name='frozen',
            field=models.BooleanField(default=False),
        ),
    ]
